### ISSUE TITLE
Support Building Local Dockerfiles

### ISSUE THREAD

**Issue by jpulec** [Trendyol/jest-testcontainers#27]
`testcontainers-node` supports building local Dockerfiles and even using Docker Compose to build and run several containers. This can be really useful for doing End-to-End testing with Jest.

Is this something that might be worth adding to `jest-testcontainers`?

**Comment by Yengas** [comment]
Hey @jpulec,

This is a cool idea. It could be similar to jest + puppeteer where people build e2e tests to their Docker container. Since `testcontainers-node` supports it, it should be fairly easy to implement.

If you were to start implementing something like this, I would do my best to review and get it merged to the master branch.

Regards,
